### ISSUE TITLE
FEAT: Make the admin screen to manage the all things

### ISSUE THREAD

**Issue by AnthonyLoche** [HackHeaders/FrontEnd#67]
📃 **Description** 📃:

- Make the admin screen to manage the all things;
- First, you not need connect with the backend;

✅ **Checklist** ✅:

`Peraza`
- [x] Install the echarts package;
- [x] Choice the types of graphs;
- [x] Create the fake arrays to you can make graphs;
- [x] Make the graphs;
- [x] Put the graphs in the sections;
- [x] Commit;

`Scrum Master (Anthony)`
- [x] Create the view into admin folder;
- [x] Create the route;
- [x] Make the components;
- [ ] Import to the view;
- [ ] Commit;

`All`
- Open Pull Request;

⚠️ **Notes (IMPORTANT)** ⚠️:

- Create your branch with the name `Feat-(number of your branch)`, based on the `dev` branch (ALWAYS based on `dev`);
- Branch `Dev` and `Main` have a protection rule, so nobody can commit to these branches (except me);
- When it is make your commit, use #Issue-Number, to you reference you issue; 
- After you finish your task, check the checklist, move your task to "In Review" in the Kanban Project;
- In the end, make a pull request to `Dev`;
- `NÃO É PERMITIDO MACAQUISSE`

🗂️ **Archives** 🗂️:

![Image](https://github.com/user-attachments/assets/35849ed7-df7c-4bf6-b611-da19ad854058)
![Image](https://github.com/user-attachments/assets/da4ee5f0-6fa1-4cd1-80cb-b18209b1cc37)

**Comment by jonatasperaza** [comment]
podepah
